import Head from "next/head";
import Layout from "../components/Layout";

import { Fragment } from "react";

import Shop from "../components/Shop";
import { ShopItem } from "../components/Shop/types";

export async function getStaticProps() {
  const items: ShopItem[] = [
    { name: "First Item", description: "This is the first item", price: 1000 },
    { name: "First Item", description: "This is the first item", price: 1000 },
    { name: "First Item", description: "This is the first item", price: 1000 },
    { name: "First Item", description: "This is the first item", price: 1000 },
    { name: "First Item", description: "This is the first item", price: 1000 },
    { name: "First Item", description: "This is the first item", price: 1000 },
    { name: "First Item", description: "This is the first item", price: 1000 },
  ];
  return {
    props: { items },
  };
}

type Props = {
  items: ShopItem[];
};

export default function Home({ items }: Props) {
  return (
    <Fragment>
      <Head>
        <title>Cow Collective</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Shop items={items} />
      </Layout>
    </Fragment>
  );
}
